export const expenses = {
  "2025-07-17": [
    {
      title: "Harry paid ₹300 for burgers 🍔",
      youOwe: true,
      amountOwed: 150,
      icon: "coffee",
      iconColor: "#e67e22",
    },
    {
      title: "You paid ₹400 for groceries 🛒, Harry owes you ₹200",
      youOwe: false,
      amountOwed: 200,
      icon: "gift",
      iconColor: "#ff6b81",
    },
    {
      title: "You paid ₹600 for Netflix 🎬, Alex and Sam owe you ₹200 each",
      youOwe: false,
      amountOwed: 400,
      icon: "globe",
      iconColor: "#16a085",
    },
  ],
  "2025-07-16": [
    {
      title: "Sam paid ₹500 for dinner 🍽️, you owe ₹250",
      youOwe: true,
      amountOwed: 250,
      icon: "user",
      iconColor: "#f1c40f",
    },
    {
      title: "You paid ₹700 for Uber 🚗, Sam owes ₹350",
      youOwe: false,
      amountOwed: 350,
      icon: "briefcase",
      iconColor: "#34495e",
    },
    {
      title: "Lily paid ₹300 for snacks 🍟, you owe ₹150",
      youOwe: true,
      amountOwed: 150,
      icon: "coffee",
      iconColor: "#e67e22",
    },
    {
      title: "You paid ₹1000 for rent 🏠, Alex and Harry owe ₹500",
      youOwe: false,
      amountOwed: 1000,
      icon: "wifi",
      iconColor: "#e74c3c",
    },
    {
      title: "Alex paid ₹200 for chai ☕, you owe ₹100",
      youOwe: true,
      amountOwed: 100,
      icon: "moon",
      iconColor: "#3498db",
    },
  ],
  "2025-07-12": [
    {
      title: "You paid ₹800 for office supplies 📦, team owes ₹800",
      youOwe: false,
      amountOwed: 800,
      icon: "briefcase",
      iconColor: "#34495e",
    },
    {
      title: "Harry paid ₹600 for lunch 🍱, you owe ₹200",
      youOwe: true,
      amountOwed: 200,
      icon: "headphones",
      iconColor: "#9b59b6",
    },
    {
      title: "Lily paid ₹400 for dessert 🍨, you owe ₹200",
      youOwe: true,
      amountOwed: 200,
      icon: "coffee",
      iconColor: "#e67e22",
    },
    {
      title: "You paid ₹300 for petrol ⛽, Lily owes ₹150",
      youOwe: false,
      amountOwed: 150,
      icon: "activity",
      iconColor: "#2ecc71",
    },
    {
      title: "Sam paid ₹500 for cleaning 🧹, you owe ₹250",
      youOwe: true,
      amountOwed: 250,
      icon: "user",
      iconColor: "#f1c40f",
    },
    {
      title: "You paid ₹250 for coffee run ☕, everyone owes ₹50",
      youOwe: false,
      amountOwed: 200,
      icon: "coffee",
      iconColor: "#e67e22",
    },
    {
      title: "Alex paid ₹1000 for AC service ❄️, you owe ₹500",
      youOwe: true,
      amountOwed: 500,
      icon: "gift",
      iconColor: "#ff6b81",
    },
  ],
};
